name: Check for update from realm/realm-swift repository

on:
  workflow_call:
    inputs:
      source-repo:
        description: 'Source repository to check'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release
        id: latest_release
        run: |
          LATEST_RELEASE=$(curl --silent "https://api.github.com/repos/${{ inputs.source-repo }}/releases/latest" | jq -r .tag_name)
          echo "VERSION=${LATEST_RELEASE}" >> $GITHUB_OUTPUT

      - name: Compare with latest release in our repo
        id: compare_release
        run: |
          NEW_VERSION="${{ steps.latest_release.outputs.version }}"
          CURRENT_VERSION=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r .tag_name)
          if [ "$NEW_VERSION" == "$CURRENT_VERSION" ]; then
            echo "The latest release from ${{ inputs.source-repo }} is already processed in our repository. Exiting the workflow."
            exit 0
          fi
          echo "CALL_WORKFLOW=true" >> $GITHUB_OUTPUT
         