name: Check for update from realm/realm-swift repository

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # This schedule is set to run every day at midnight. Modify as necessary.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release
        id: latest_release
        run: |
          LATEST_RELEASE=$(curl --silent "https://api.github.com/repos/realm/realm-swift/releases/latest" | jq -r .tag_name)
          echo "::set-output name=version::${LATEST_RELEASE}"

      - name: Compare with latest release in our repo
        run: |
          NEW_VERSION="${{ steps.latest_release.outputs.version }}"
          CURRENT_VERSION=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r .tag_name)
          if [ "$NEW_VERSION" == "$CURRENT_VERSION" ]; then
            echo "The latest release from realm/realm-swift is already processed in our repository. Exiting the workflow."
            exit 0
          fi

      - name: Call the update-package workflow
        uses: ./.github/workflows/update-package.yml
         