name: Check for update from realm/realm-swift repository

on:
  workflow_call:
    inputs:
      source-repo:
        description: 'Source repository to check'
        required: true
        type: string
    outputs:
      latest-version:
        description: "The latest relase of the source repository"
        value: ${{ jobs.check-version.outputs.latest-version }}
      needs-update:
        description: "True if the latest version is not our latest version"
        value:  ${{ jobs.check-version.outputs.needs-update }}

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      latest-version: ${{ steps.latest_release.outputs.latest-version }}
      needs-update: ${{ steps.compare_release.outputs.needs-update }}
    steps:
      - name: Get latest release
        id: latest_release
        run: |
          LATEST_RELEASE=$(curl --silent "https://api.github.com/repos/${{ inputs.source-repo }}/releases/latest" | jq -r .tag_name)
          echo "latest-version=${LATEST_RELEASE}" >> $GITHUB_OUTPUT

      - name: Compare with latest release in our repo
        id: compare_release
        run: |
          NEW_VERSION="${{ steps.latest_release.outputs.latest-version }}"
          CURRENT_VERSION=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r .tag_name)
          if [ "$NEW_VERSION" == "$CURRENT_VERSION" ]; then
            echo "The latest release from ${{ inputs.source-repo }} is already processed in our repository. Exiting the workflow."
            echo "needs-update=false" >> $GITHUB_OUTPUT
          else
            echo "Needs an update"
            echo "needs-update=true" >> $GITHUB_OUTPUT
            echo "$GITHUB_OUTPUT"
          fi

      - name: Print out stuff
        run: |
          echo " Needs update is set to ${{ steps.compare_release.outputs.needs-update}}"

      - name: Check out code
        if: steps.compare_release.outputs.needs-update == 'true'
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}    

      - name: "Download xcframeworks"
        if: steps.compare_release.outputs.needs-update == 'true'
        id: download_xcframeworks
        run: |
          mkdir downloads
          ASSET_URLS=$(curl -s https://api.github.com/repos/realm/realm-swift/releases/latest | jq -r '.assets[] | select(.name | endswith(".xcframework.zip")) | .browser_download_url')
          for url in $ASSET_URLS; do
            (cd downloads; curl -sLJO $url)
          done
          ls -l downloads