name: Create new release

on:
  workflow_call:
    inputs:
      version:
        description: 'New version to use for release'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Commit and push changes
        run: |
          git config --local user.email github-actions@github.com
          git config --local user.name github-actions
          git add Package.swift
          git commit -m "Update Package.swift for release ${{ inputs.version }}"
          git push
          git tag ${{ inputs.version }}
          git push --tags
  
      - name: Create new release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ inputs.version }}"
          release_name: "${{ inputs.version }}"
          draft: false
          prerelease: false

      - name: Upload Release Assets
        run: |
          find . -name "xcframeworks/*.zip" -exec bash -c '
            curl \
            -H "Authorization: token $0" \
            -H "Content-Type: $(file -b --mime-type $1)" \
            --data-binary @"$1" \
            "https://uploads.github.com/repos/$2/releases/$3/assets?name=$(basename $1)"
          ' "${{ secrets.GITHUB_TOKEN }}" {} "${{ github.repository }}" "${{ steps.create_release.outputs.id }}" \;