name: Process latest realm-swift release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # This schedule is set to run every day at midnight. Modify as necessary.

jobs:
  check_for_updates:
    name: "Call the update-package workflow"
    uses: ./.github/workflows/check-for-update.yml
    with:
      source-repo: 'realm/realm-swift'

  build:
    needs: check_for_updates
    if: needs.check_for_updates.outputs.needs-update == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}

      - name: Download and process frameworks
        id: process_frameworks
        run: |
          mkdir downloads
          ASSET_URLS=$(curl -s https://api.github.com/repos/realm/realm-swift/releases/latest | jq -r '.assets[] | select(.name | endswith(".spm.zip")) | .browser_download_url')
          for url in $ASSET_URLS; do
            (cd downloads; curl -sLJO $url)
          done
 
      - name: Update Package.swift files.
        run: |
          NEW_VERSION="${{ needs.check_for_updates.outputs.latest-version }}"
          CHECKSUM_REALM=$(shasum -a 256 downloads/Realm.spm.zip | awk '{ print $1 }')
          REALM_URL="https://github.com/realm/realm-swift/releases/download/$NEW_VERSION/Realm.spm.zip"

          CHECKSUM_REALMSWIFT=$(shasum -a 256 downloads/RealmSwift@14.3.1.spm.zip | awk '{ print $1 }')
          REALMSWIFT_URL="https://github.com/realm/realm-swift/releases/download/$NEW_VERSION/RealmSwift@14.3.1.spm.zip"

          sed -i \
              -e "s|let realmURL = \".*\"|let realmURL = \"$REALM_URL\"|" \
              -e "s|let realmChecksum = \".*\"|let realmChecksum = \"$CHECKSUM_REALM\"|" \
              -e "s|let realmSwiftURL = \".*\"|let realmSwiftURL = \"$REALMSWIFT_URL\"|" \
              -e "s|let realmSwiftChecksum = \".*\"|let realmSwiftChecksum = \"$CHECKSUM_REALMSWIFT\"|" \
              Package.swift

            sed -i \
              -e "s|let realmURL = \".*\"|let realmURL = \"$REALM_URL\"|" \
              -e "s|let realmChecksum = \".*\"|let realmChecksum = \"$CHECKSUM_REALM\"|" \
              -e "s|let realmSwiftURL = \".*\"|let realmSwiftURL = \"$REALMSWIFT_URL\"|" \
              -e "s|let realmSwiftChecksum = \".*\"|let realmSwiftChecksum = \"$CHECKSUM_REALMSWIFT\"|" \
              Package@swift-5.8.swift

          CHECKSUM_REALMSWIFT=$(shasum -a 256 downloads/RealmSwift@15.0.spm.zip | awk '{ print $1 }')
          REALMSWIFT_URL="https://github.com/realm/realm-swift/releases/download/$NEW_VERSION/RealmSwift@15.0.spm.zip"

          sed -i \
              -e "s|let realmURL = \".*\"|let realmURL = \"$REALM_URL\"|" \
              -e "s|let realmChecksum = \".*\"|let realmChecksum = \"$CHECKSUM_REALM\"|" \
              -e "s|let realmSwiftURL = \".*\"|let realmSwiftURL = \"$REALMSWIFT_URL\"|" \
              -e "s|let realmSwiftChecksum = \".*\"|let realmSwiftChecksum = \"$CHECKSUM_REALMSWIFT\"|" \
              Package@swift-5.9.swift


  
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updates Package.swift files for release ${{ needs.check_for_updates.outputs.latest-version }}
          tagging_message: ${{ needs.check_for_updates.outputs.latest-version }}
  
      - name: Create new release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ needs.check_for_updates.outputs.latest-version }}"
          release_name: "${{ needs.check_for_updates.outputs.latest-version }}"
          draft: false
          prerelease: false
