name: Process latest realm-swift release

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release
        id: latest_release
        run: |
          LATEST_RELEASE=$(curl --silent "https://api.github.com/repos/realm/realm-swift/releases/latest" | jq -r .tag_name)
          echo "::set-output name=version::${LATEST_RELEASE}"

      - name: Compare with latest release in our repo
        run: |
          NEW_VERSION="${{ steps.latest_release.outputs.version }}"
          CURRENT_VERSION=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r .tag_name)
          if [ "$NEW_VERSION" == "$CURRENT_VERSION" ]; then
            echo "::warning::The latest release from realm/realm-swift is already processed in our repository. Exiting the workflow."
            exit 1
          fi

      - name: Check out code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}

      - name: Download and process frameworks
        id: process_frameworks
        run: |
          ASSET_URLS=$(curl -s https://api.github.com/repos/realm/realm-swift/releases/latest | jq -r '.assets[] | select(.name | endswith(".xcframework.zip")) | .browser_download_url')
          for url in $ASSET_URLS; do
            curl -sLJO $url
            FILENAME=$(basename $url)
            SHA256_HASH=$(shasum -a 256 $FILENAME | cut -f 1 -d ' ')
            echo "::set-output name=${FILENAME%%.zip}::$SHA256_HASH"
          done
 
      - name: Update Package.swift
        run: |
          NEW_VERSION="${{ steps.latest_release.outputs.version }}"
          CHECKSUM_REALM=$(shasum -a 256 Realm.xcframework.zip | awk '{ print $1 }')
          CHECKSUM_REALMSWIFT=$(shasum -a 256 RealmSwift@15.0.xcframework.zip | awk '{ print $1 }')

          REALM_URL="https://github.com/realm/realm-swift/releases/download/$NEW_VERSION/Realm.xcframework.zip"
          REALMSWIFT_URL="https://github.com/realm/realm-swift/releases/download/$NEW_VERSION/RealmSwift@15.0.xcframework.zip"

          sed -i.bak \
              -e "s|let realmURL = \".*\"|let realmURL = \"$REALM_URL\"|" \
              -e "s|let realmChecksum = \".*\"|let realmChecksum = \"$CHECKSUM_REALM\"|" \
              -e "s|let realmSwiftURL = \".*\"|let realmSwiftURL = \"$REALMSWIFT_URL\"|" \
              -e "s|let realmSwiftChecksum = \".*\"|let realmSwiftChecksum = \"$CHECKSUM_REALMSWIFT\"|" \
              Package.swift

          rm Package.swift.bak
  
      - name: Commit and push changes
        run: |
          git config --local user.email github-actions@github.com
          git config --local user.name github-actions
          git add Package.swift
          git commit -m "Update Package.swift for release ${{ steps.latest_release.outputs.version }}"
          git push
          git tag ${{ steps.latest_release.outputs.version }}
          git push --tags
  
      - name: Create new release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ steps.latest_release.outputs.version }}"
          release_name: "${{ steps.latest_release.outputs.version }}"
          draft: false
          prerelease: false
